### ISSUE TITLE
Unload DateTime using internal Starcounter format, and not the ticks

### ISSUE THREAD

**Issue by miyconst** [Starcounter/StarDump.Migrator.2.2#1]
Currently the tool unloads `DateTime` values in `Ticks` which might be not correct, since the `StarDump` tool uses internal Starcounter values.

@k-rus how to get the internal Starcounter value per `DateTime` value? I remember you told something on the last release meeting, but connection was so poor, that I could not understand, sorry for that.

@ubbeK please follow up with the issue and update the [SqlHelper.ConvertFromStarcounterToSqlite](https://github.com/Starcounter/StarDump.Migrator.2.2/blob/master/src/StarDump.Migrator.2.2/Helpers/SqlHelper.cs#L45) method.

**Comment by k-rus** [comment]
> The semantics of the value can be understood by the code host, which contains value translation to and from DateTime.
> Could you please point to the code lines where to look for it? From Starcounter.Core.DbType class I can see that the value is the number of ticks.
> 
> Starcounter.Core.DbType.GetDateTime.
> 
> If this is correct, then we don't have to change anything, as currently this is the value being unloaded.

I meant Level1 code host, since I haven't dealt with Starcounter.Core implementation. I believe both implementations use number of ticks. (Level1 uses number of ticks)

**Comment by miyconst** [comment]
Good. Then this issue is already solved.
