### ISSUE TITLE
StarDump.Migrator.2.2 has been successfully uploaded to warehouse

### ISSUE THREAD

**Issue by ubbeK** [Starcounter/StarDump.Migrator.2.2#4]
StarDump.Migrator.2.2 version `0.1.0` has been successfully uploaded to warehouse under `Starcounter Developer Samples store`. 

![warehouse](https://cloud.githubusercontent.com/assets/8124023/21591667/8f9d61d4-d106-11e6-8870-41decb50981b.PNG)

**Comment by andwah** [comment]
Nice!.

@warpech has fix a subscription for us to an online icon library called https://thenounproject.com/  there you can find and download a nice icon for StarDump (download the .svg for the app icon)

Icons are black and white and can look like this:
![image](https://cloud.githubusercontent.com/assets/2656996/21602637/73dc6b9e-d196-11e6-9b8f-8bb52ff0f815.png)![image](https://cloud.githubusercontent.com/assets/2656996/21602719/6261a6f8-d197-11e6-9127-dc5514cd3c38.png)![image](https://cloud.githubusercontent.com/assets/2656996/21602763/cde53fc0-d197-11e6-85dc-4e3873a825b1.png)

**Comment by ubbeK** [comment]
@andwah Great, thanks! Exactly what I was looking for.

**Comment by ubbeK** [comment]
I am going to the `transfer database` icon from `Database _ Thin` collection by `sevgenjory`

![noun_668988](https://cloud.githubusercontent.com/assets/8124023/21649540/67087c16-d2a2-11e6-9b84-1993b1884944.png)

**Comment by ubbeK** [comment]
![warehouse_stardump_migration_2_2](https://cloud.githubusercontent.com/assets/8124023/21650640/e9345022-d2a5-11e6-9a20-f428ff120071.PNG)

patch with new icon uploaded, closing issue

**Comment by warpech** [comment]
I thought you will actually use the escalator icon ;)

**Comment by ubbeK** [comment]
nahh... the dumpster-truck would be a better fit

**Comment by warpech** [comment]
Ha! Or a moving truck! :)
