### ISSUE TITLE
System.NullReferenceException,  private property "_LastName" from Simplified.Ring2.Person was included as a column to unload

### ISSUE THREAD

**Issue by andwah** [Starcounter/StarDump.Migrator.2.2#5]
When i try to unload a database i get an error:
```
System.NullReferenceException: Objektreferensen har inte angetts till en instans av ett objekt.
   vid StarDump.Migrator22.UnloadTable.FillRow(DumpRow row, Object obj) i c:\github\Starcounter\StarDump.Migrator.2.2\src\StarDump.Migrator.2.2\Model\UnloadTable.cs:rad 44
   vid StarDump.Migrator22.Unload.<>c__DisplayClass12_0.<Run>b__1() i c:\github\Starcounter\StarDump.Migrator.2.2\src\StarDump.Migrator.2.2\Unload.cs:rad 82
   vid Starcounter.Db.Transact(Action action, UInt32 flags, Boolean forceSnapshot, Int32 maxRetries) i C:\github\Starcounter\Level1\src\Starcounter\Db.cs:rad 355
   vid Starcounter.Db.Transact(Action action, Boolean forceSnapshot, Int32 maxRetries) i C:\github\Starcounter\Level1\src\Starcounter\Db.cs:rad 162
   vid StarDump.Migrator22.Unload.<>c__DisplayClass12_0.<Run>b__0() i c:\github\Starcounter\StarDump.Migrator.2.2\src\StarDump.Migrator.2.2\Unload.cs:rad 51
   vid Starcounter.Internal.StarcounterEnvironment.RunWithinApplication(String desiredAppName, Action action) i C:\github\Starcounter\Level1\src\Starcounter.Internal\Mock\StarcounterEnvironment.cs:rad 128
   vid StarDump.Migrator22.Unload.Run() i c:\github\Starcounter\StarDump.Migrator.2.2\src\StarDump.Migrator.2.2\Unload.cs:rad 49
   vid StarDump.Migrator22.Handlers.<>c.<Register>b__0_0(String dumpPath) i c:\github\Starcounter\StarDump.Migrator.2.2\src\StarDump.Migrator.2.2\Handlers.cs:rad 23
   vid lambda_method(Closure , Request , IntPtr , IntPtr )
   vid Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) i C:\github\Starcounter\Level1\src\Starcounter.Rest\UriHandlersManager.cs:rad 221
   vid Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) i C:\github\Starcounter\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:rad 98
   vid Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) i C:\github\Starcounter\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:rad 765
HResult=-2147467261

More information about this error may be available in the server error log.
```

The class `Simplified.Ring2.Person` has a private field `_LastName` that it tries to get the value from.

**Comment by miyconst** [comment]
@ubbeK would you have time to take a look and find a workaround? Assign on me otherwise.

**Comment by andwah** [comment]
`SELECT c FROM Starcounter.Metadata.Column c` do return the "_LastName" field,  maybe my database has some "old" fields laying around.

**Comment by miyconst** [comment]
>... maybe my database has some "old" fields laying around.

In this case we can't properly unload such database. We can either fall with a proper exception or unload the database without those values.

**Comment by ubbeK** [comment]
I did not plan on working anymore until Monday. 

@andwah: How urgent is it?

**Comment by andwah** [comment]
@ubbeK Not urgent at all, i was just wanted to test the tool :-)

**Comment by miyconst** [comment]
>We can either fall with a proper exception or unload the database without those values.

@andwah what would you prefer? Were you able to solve the problem by providing CLR classes the same as database structure underneath?

**Comment by andwah** [comment]
> Were you able to solve the problem by providing CLR classes the same as database structure underneath?

I did not tests that, i only adding classes without any properties then i was hit by this https://github.com/Starcounter/StarDump.Migrator.2.2/issues/7

Now that https://github.com/Starcounter/StarDump.Migrator.2.2/issues/7 is solved i will try again.


> We can either fall with a proper exception or unload the database without those values.

I Prefer to Unload without those values, and maybe some warning about it? but no Exception

**Comment by miyconst** [comment]
>I Prefer to Unload without those values, and maybe some warning about it? but no Exception.

Okay. I will implement it till Monday.

**Comment by miyconst** [comment]
@andwah the problem was with the `_LastName`, it is a private field, not a public property which I expected. 

Now the tool supports properties and fields, including non public ones. Also it skips the unavailable columns and informs about it in the run result.

Please check.

**Comment by ubbeK** [comment]
I will rerelease the Migrator tool during the day.

**Comment by miyconst** [comment]
Please do so after @andwah confirms the fix.

**Comment by ubbeK** [comment]
@andwah Did you get the chance to confirm this fix? There has been several other fixes the past two days aswell.

**Comment by andwah** [comment]
not yet, i will try again to do an unload and reload.
