### ISSUE TITLE
Create new 0.1.2 version and publish it on old warehouse

### ISSUE THREAD

**Issue by ubbeK** [Starcounter/StarDump.Migrator.2.2#9]

**Comment by miyconst** [comment]
@ubbeK please also update [this value](https://github.com/Starcounter/StarDump.Migrator.2.2/blob/master/src/StarDump.Migrator.2.2/Assembly.cs#L5) when releasing a version.

**Comment by ubbeK** [comment]
closing this, invalid because of #14
